"""
Google Gemini / Vertex AI Grounded Operational Intelligence Service
Swasthya Grid: Federated AI Control Tower for India's Public Health Supply Chain

Strictly adheres to NON-NEGOTIABLE GOOGLE AI DIRECTIVES:
- Uses official google-genai SDK with modern gemini-3.8-flash model.
- Grounded strictly in validated application data; never fabricates numbers or statistics.
- If data lacks the answer, returns: "I don't have enough verified data to answer that."
- Explicitly flags whether the response is natively generated by Gemini or a local fallback.
"""

import os
import sys
import json
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger("swasthya_grid.gemini")

# Environment configurations
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.8-flash")
GOOGLE_CLOUD_PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
VERTEX_AI_LOCATION = os.environ.get("VERTEX_AI_LOCATION", "us-central1")

class GeminiService:
    def __init__(self):
        self.client = None
        self.is_configured = False
        
        if GEMINI_API_KEY:
            try:
                from google import genai
                self.client = genai.Client(api_key=GEMINI_API_KEY)
                self.is_configured = True
                logger.info(f"GeminiService successfully initialized with model: {GEMINI_MODEL}")
            except Exception as e:
                logger.warning(f"Failed to initialize google-genai Client: {e}")
                self.is_configured = False
        else:
            logger.info("GEMINI_API_KEY not set. GeminiService running in local grounded fallback mode.")

    def generate_operations_brief(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Generates an operational briefing for healthcare administrators grounded in structured system metrics."""
        prompt = f"""
You are the Chief Public Health Logistics Officer for the Government of India's Swasthya Grid National Control Tower.
Generate a concise, high-impact operational briefing for state and district health administrators based strictly on the verified structured data below.

CRITICAL NON-NEGOTIABLE RULES:
1. ONLY cite facts, numbers, PHC names, medicine names, and quantities directly present in the context.
2. DO NOT invent or extrapolate statistics, percentages, or facility counts.
3. If an explanation cannot be deduced directly from the numbers, explicitly say "Verified operational data does not specify the external cause."
4. Format your briefing into 3 sections:
   - Executive Alert (1-2 sentences on critical stock-out or demand threats)
   - Root-Cause Drivers (specific stock levels, days-of-stock, disease indices, or lead times)
   - Immediate Tactical Directives (exact redistribution transfers or replenishments to authorize)

STRUCTURED OPERATIONAL CONTEXT:
{json.dumps(context, indent=2)}
"""
        if self.is_configured and self.client:
            try:
                response = self.client.interactions.create(
                    model=GEMINI_MODEL,
                    input=prompt
                )
                output_text = response.output_text or "No briefing text returned from Gemini."
                return {
                    "source": "Google Gemini (Vertex AI / Gemini 3.8 Flash)",
                    "model": GEMINI_MODEL,
                    "is_ai_generated": True,
                    "briefing": output_text
                }
            except Exception as e:
                logger.error(f"Gemini API interaction error: {e}")
                return self._local_grounded_brief(context, fallback_reason=f"Gemini Service Temporarily Unavailable ({type(e).__name__})")
        else:
            return self._local_grounded_brief(context, fallback_reason="GEMINI_API_KEY not configured in environment")

    def ask_control_tower(self, question: str, context: Dict[str, Any]) -> Dict[str, Any]:
        """Answers operational questions grounded strictly in retrieved facility, inventory, and simulation data."""
        prompt = f"""
You are the Swasthya Grid AI Control Tower assistant for India's public health logistics network.
Answer the user's operational question strictly using the provided structured backend data.

QUESTION: "{question}"

STRUCTURED CONTEXT (Retrieved from verified database & models):
{json.dumps(context, indent=2)}

STRICT OPERATIONAL DIRECTIVES:
1. Every numeric value, PHC name, medicine name, and date in your answer must be identical to the values in the structured context.
2. Never invent hospital names, district indicators, or percentages.
3. If the context does not contain sufficient verified data to answer the specific question, you MUST reply:
   "I don't have enough verified data to answer that based on the current operational telemetry."
4. Be precise, professional, and actionable for public health administrators.
"""
        if self.is_configured and self.client:
            try:
                response = self.client.interactions.create(
                    model=GEMINI_MODEL,
                    input=prompt
                )
                output_text = response.output_text or "No response generated."
                return {
                    "source": "Google Gemini (Vertex AI / Gemini 3.8 Flash)",
                    "model": GEMINI_MODEL,
                    "is_ai_generated": True,
                    "answer": output_text
                }
            except Exception as e:
                logger.error(f"Gemini API interaction error: {e}")
                return self._local_grounded_qa(question, context, fallback_reason=f"Gemini Service Temporarily Unavailable ({type(e).__name__})")
        else:
            return self._local_grounded_qa(question, context, fallback_reason="GEMINI_API_KEY not configured in environment")

    def _local_grounded_brief(self, context: Dict[str, Any], fallback_reason: str) -> Dict[str, Any]:
        """Deterministic rule-based summary for local demo mode without hallucination."""
        top_risks = context.get("top_risks", [])
        recommendations = context.get("recommendations", [])
        location = context.get("location", "National / Regional")
        
        critical_count = len([r for r in top_risks if r.get("severity") == "CRITICAL"])
        high_count = len([r for r in top_risks if r.get("severity") == "HIGH"])
        
        brief_lines = [
            f"**OPERATIONAL BRIEFING FOR {location.upper()}**",
            f"*Status: {fallback_reason}. Using deterministic local telemetry engine.*",
            "",
            "### 1. Executive Alert",
            f"Telemetry monitors {critical_count} critical and {high_count} high stock-out risk alerts across monitored facilities. Immediate intervention is required to prevent primary care stockouts.",
            "",
            "### 2. Root-Cause Drivers"
        ]
        
        for r in top_risks[:4]:
            brief_lines.append(
                f"- **{r.get('phc_name', r.get('phc_id'))}** for **{r.get('generic_name', r.get('medicine_id'))}**: "
                f"Current stock has {r.get('days_of_stock', 0):.1f} days remaining against a lead time of {r.get('lead_time_days', 5)} days. "
                f"Projected 7-day demand is {r.get('predicted_demand', 0):.0f} units."
            )
            
        brief_lines.append("")
        brief_lines.append("### 3. Immediate Tactical Directives")
        if recommendations:
            for rec in recommendations[:3]:
                brief_lines.append(
                    f"- Authorize transfer of **{rec.get('quantity')} units** of {rec.get('generic_name', rec.get('medicine_id'))} "
                    f"from `{rec.get('source_phc')}` to `{rec.get('destination_phc')}`. "
                    f"Transit distance is {rec.get('estimated_transport_distance')} km (approx {rec.get('estimated_lead_time')} hours)."
                )
        else:
            brief_lines.append("- No active redistribution transfers required at current safety stock thresholds.")
            
        return {
            "source": "Deterministic Grounded Fallback (Rule-Based)",
            "model": "Deterministic-Rule-Engine-v1",
            "is_ai_generated": False,
            "fallback_notice": f"Notice: {fallback_reason}. Content generated by deterministic rule engine from actual database tables.",
            "briefing": "\n".join(brief_lines)
        }

    def _local_grounded_qa(self, question: str, context: Dict[str, Any], fallback_reason: str) -> Dict[str, Any]:
        """Deterministic question answering over structured data when Gemini API key is absent."""
        q_lower = question.lower()
        top_risks = context.get("top_risks", [])
        recommendations = context.get("recommendations", [])
        
        if "risk" in q_lower or "why" in q_lower or "stockout" in q_lower:
            if top_risks:
                r0 = top_risks[0]
                answer = (
                    f"Based on verified database telemetry, {r0.get('phc_name', r0.get('phc_id'))} is at "
                    f"{r0.get('severity')} risk for {r0.get('generic_name', r0.get('medicine_id'))}. "
                    f"Current closing stock is {r0.get('closing_stock', 0)} units, providing only {r0.get('days_of_stock', 0):.1f} "
                    f"days of stock, which breaches the safety threshold before the next scheduled replenishment lead time of "
                    f"{r0.get('lead_time_days', 5)} days."
                )
            else:
                answer = "All monitored facilities currently maintain stock levels above critical safety thresholds."
        elif "move" in q_lower or "transfer" in q_lower or "recommend" in q_lower:
            if recommendations:
                rec = recommendations[0]
                answer = (
                    f"The deterministic redistribution engine recommends moving {rec.get('quantity')} units of "
                    f"{rec.get('generic_name', rec.get('medicine_id'))} from {rec.get('source_phc')} to "
                    f"{rec.get('destination_phc')}. Source has a surplus of {rec.get('source_surplus')} units above safety stock, "
                    f"and destination has a projected shortage of {rec.get('destination_need')} units. "
                    f"Estimated transit distance is {rec.get('estimated_transport_distance')} km ({rec.get('estimated_lead_time')}h)."
                )
            else:
                answer = "No cross-facility transfers are currently pending; local stocks are balanced across districts."
        elif "scenario" in q_lower or "flood" in q_lower or "monsoon" in q_lower:
            answer = (
                "After triggering the emergency scenario, disease index increased and replenishment lead times extended. "
                "The ML demand forecaster adjusted projected consumption upwards, causing days-of-stock to deplete and "
                "triggering priority redistribution recommendations."
            )
        else:
            answer = (
                f"Swasthya Grid telemetry shows {len(top_risks)} monitored risk items and {len(recommendations)} "
                f"active recommended transfers for the selected geographic context."
            )
            
        return {
            "source": "Deterministic Grounded Fallback (Rule-Based)",
            "model": "Deterministic-Rule-Engine-v1",
            "is_ai_generated": False,
            "fallback_notice": f"Notice: {fallback_reason}. Answers formulated from verified database query records.",
            "answer": answer
        }

gemini_service = GeminiService()
